IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'USERINFO')
BEGIN
CREATE TABLE  USERINFO
(
	UserId VARCHAR(200) NOT NULL UNIQUE,
	UserName VARCHAR(200),
	EmailId  VARCHAR(200)
);
END;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'USERS')
BEGIN
CREATE TABLE USERS
(
	UserId VARCHAR(200) NOT NULL UNIQUE,
	Password VARCHAR(200)
);
END;